services:
  - type: web
    name: strabismus-ml-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
